steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
  '-t',
  'gcr.io/my-project-id/myimage',
  '.',
  '--build-arg',
  'COOKIE_SECRET_PREVIOUS="_SUB_COOKIE_SECRET_PREVIOUS"',
  '--build-arg',
  'COOKIE_SECRET_CURRENT="_SUB_COOKIE_SECRET_CURRENT"',
  '--build-arg',
  'NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY="_SUB_NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY"',
  '--build-arg',
  'NEXT_PUBLIC_FIREBASE_APP_NAME="_SUB_NEXT_PUBLIC_FIREBASE_APP_NAME"',
  '--build-arg',
  'NEXT_PUBLIC_API_HOST="_SUB_NEXT_PUBLIC_API_HOST"'
  ]
